import { createId } from "@paralleldrive/cuid2";
import type { ProjectFontRole } from "#/features/editor/font-system/font-system.types";
import { getCardSizeFromAspectRatio } from "#/features/editor/lib/card-size";
import type { CardAspectRatio, CardSettings, EditorCard, TextAlignment, TextCasing, TypographyScenarioCategory, TypographyStressTest } from "#/features/editor/types";

export type ScenarioTextPurpose = "display" | "heading" | "body" | "caption" | "metadata" | "label" | "numeral";
export type ScenarioTextNodeBlueprint = {
	type: "text"; key: string; role: ProjectFontRole; purpose: ScenarioTextPurpose;
	content: string; x: number; y: number; width: number; height: number;
	fontSize: number; fontWeight?: number; lineHeight: number; letterSpacing?: number;
	textAlign?: TextAlignment; textCasing?: TextCasing; color?: string;
};
export type ScenarioImageNodeBlueprint = { type: "image"; key: string; x: number; y: number; width: number; height: number; src?: string; alt?: string };
export type ScenarioCardBlueprint = { settings?: Partial<CardSettings>; nodes: Array<ScenarioTextNodeBlueprint | ScenarioImageNodeBlueprint> };
export type TypographyScenarioDefinition = {
	id: string; name: string; description: string; category: TypographyScenarioCategory;
	purpose: string; stressTests: TypographyStressTest[]; aspectRatio: CardAspectRatio;
	card: ScenarioCardBlueprint; recommendedRoles: Partial<Record<ProjectFontRole, string>>;
};

const roles = { primary: "Display and headings", "secondary-one": "Body and supporting copy", "secondary-two": "Labels and metadata" } as const;
const text = (key: string, role: ProjectFontRole, purpose: ScenarioTextPurpose, content: string, x: number, y: number, width: number, height: number, fontSize: number, extra: Partial<ScenarioTextNodeBlueprint> = {}): ScenarioTextNodeBlueprint => ({ type: "text", key, role, purpose, content, x, y, width, height, fontSize, fontWeight: 500, lineHeight: 1.1, letterSpacing: 0, textAlign: "left", textCasing: "none", color: "#161616", ...extra });

export const TYPOGRAPHY_SCENARIOS: TypographyScenarioDefinition[] = [
	{ id:"movie-poster", name:"Movie poster", description:"A cinematic title system with tagline, credits, and date.", category:"display", purpose:"Test display scale, tight all-caps spacing, credits, dates, and image overlay.", stressTests:["display-size","all-caps","kerning","image-overlay"], aspectRatio:"4:5", recommendedRoles:roles, card:{ settings:{fill:{type:"solid",color:"#E9E3D8"}}, nodes:[text("title","primary","display","THE LAST HORIZON",32,80,336,150,58,{fontWeight:700,textCasing:"uppercase",letterSpacing:-2}),text("tagline","secondary-one","caption","EVERY DISTANCE LEAVES A MARK",34,250,300,34,13,{letterSpacing:1.4}),text("credits","secondary-two","metadata","A NORTHLIGHT FILM  ·  OCTOBER 18",34,440,330,24,9,{letterSpacing:1})]}},
	{ id:"album-cover", name:"Album cover", description:"Expressive title and sparse artist metadata.", category:"display", purpose:"Test extreme alignment, short text, display scale, and image relationships.", stressTests:["display-size","kerning","image-overlay"], aspectRatio:"1:1", recommendedRoles:roles, card:{settings:{fill:{type:"solid",color:"#D8FF3E"}},nodes:[text("title","primary","display","AFTER / IMAGE",28,36,344,210,64,{fontWeight:700,letterSpacing:-2.5}),text("artist","secondary-one","heading","MARA NINE",28,330,220,30,16,{letterSpacing:2}),text("catalogue","secondary-two","metadata","PLAIN 004 · 2026",270,366,104,18,9,{textAlign:"right"})]}},
	{ id:"campaign-headline", name:"Campaign headline", description:"A forceful multiline public-facing statement.", category:"display", purpose:"Test multiline hierarchy, punctuation, and narrow versus wide measure.", stressTests:["display-size","punctuation","narrow-container","wide-container"], aspectRatio:"16:9", recommendedRoles:roles, card:{settings:{fill:{type:"solid",color:"#FF5A36"}},nodes:[text("eyebrow","secondary-two","label","A BETTER PUBLIC REALM",48,38,300,24,12,{letterSpacing:1.4}),text("title","primary","display","Cities should feel like they belong to everyone.",48,95,610,210,48,{fontWeight:700,lineHeight:1}),text("action","secondary-one","caption","Read the plan → common-ground.org",48,350,420,30,15)]}},
	{ id:"article-opening", name:"Article opening", description:"Headline, deck, byline, and opening paragraph.", category:"editorial", purpose:"Test reading hierarchy from headline through body opening.", stressTests:["mixed-case","long-form","punctuation","wide-container"], aspectRatio:"3:2", recommendedRoles:roles, card:{settings:{fill:{type:"solid",color:"#F7F3EA"}},nodes:[text("section","secondary-two","label","DESIGN / FIELD NOTES",44,34,250,20,10,{letterSpacing:1.2}),text("title","primary","heading","The quiet architecture of everyday attention",44,78,560,110,38,{fontWeight:650,lineHeight:1.05}),text("deck","secondary-one","body","What overlooked signs, thresholds, and pauses teach us about moving through a city.",44,205,520,55,17,{lineHeight:1.35}),text("byline","secondary-two","metadata","By Amara Cole · 8 min read",44,282,300,20,11),text("body","secondary-one","body","We rarely notice the systems that guide us until they fail. A door opens the wrong way; a platform offers no place to rest; a sign arrives one turn too late.",350,282,290,105,13,{lineHeight:1.55})]}},
	{ id:"long-form-reading", name:"Long-form reading", description:"A sustained, book-like reading sample.", category:"editorial", purpose:"Test paragraph texture, line length, line height, punctuation, and numerals.", stressTests:["long-form","dense-copy","punctuation","numerals"], aspectRatio:"4:5", recommendedRoles:roles, card:{settings:{fill:{type:"solid",color:"#FFFDF8"}},nodes:[text("title","primary","heading","The Shape of a Useful Pause",38,38,315,50,25,{fontWeight:650}),text("metadata","secondary-two","metadata","CHAPTER 03 · NOTES ON TEMPO",38,102,300,20,9,{letterSpacing:1}),text("body","secondary-one","body","At 7:42 each morning, the first bus folds around the corner. Its arrival is ordinary, but the interval before it appears has a shape of its own. People look up, check a watch, then return to the private rhythm of waiting.\n\nA typeface lives in these intervals too: between letters, between lines, and between the loud statement and the quiet explanation that follows.",38,145,315,310,14,{lineHeight:1.55})]}},
	{ id:"magazine-cover", name:"Magazine cover", description:"Competing cover lines around a strong masthead.", category:"editorial", purpose:"Test display typography against dense, small labels and competing sizes.", stressTests:["display-size","small-size","dense-copy","all-caps"], aspectRatio:"4:5", recommendedRoles:roles, card:{settings:{fill:{type:"solid",color:"#BBD6EA"}},nodes:[text("masthead","primary","display","FORM",24,20,352,80,66,{fontWeight:800,letterSpacing:-3}),text("issue","secondary-two","metadata","ISSUE 18 · SUMMER 2026",28,108,220,18,9,{letterSpacing:1}),text("title","primary","heading","THE NEW MATERIALISTS",28,230,320,100,34,{fontWeight:700,lineHeight:1}),text("cover-lines","secondary-one","caption","Inside Lagos studios\nObjects built to last\nThe return of bright colour",28,360,230,72,13,{lineHeight:1.45})]}},
	{ id:"dashboard", name:"Dashboard", description:"A compact analytics dashboard with labels and figures.", category:"product-ui", purpose:"Test small UI typography, hierarchy, labels, tables, and numerals.", stressTests:["small-size","numerals","dense-copy","wide-container"], aspectRatio:"16:9", recommendedRoles:roles, card:{settings:{fill:{type:"solid",color:"#F5F6F7"}},nodes:[text("title","primary","heading","Performance overview",30,24,300,34,22,{fontWeight:650}),text("range","secondary-two","label","LAST 30 DAYS",530,30,120,18,9,{textAlign:"right",letterSpacing:.8}),text("metric-one-label","secondary-one","label","Net revenue",30,92,180,20,11),text("metric-one","secondary-two","numeral","₦18.4M",30,118,200,48,36,{fontWeight:700}),text("metric-two-label","secondary-one","label","Conversion",250,92,180,20,11),text("metric-two","secondary-two","numeral","12.8%",250,118,180,48,36,{fontWeight:700}),text("table","secondary-one","body","CHANNEL              VISITS       RATE\nDirect                 24,892        14.2%\nSearch                 18,441        11.7%\nReferral                8,206         9.4%",30,215,610,120,12,{lineHeight:1.75})]}},
	{ id:"settings-screen", name:"Settings screen", description:"Forms, helper copy, actions, and errors.", category:"product-ui", purpose:"Test compact labels, helper text, buttons, and error-state hierarchy.", stressTests:["small-size","dense-copy","mixed-case"], aspectRatio:"3:2", recommendedRoles:roles, card:{settings:{fill:{type:"solid",color:"#FFFFFF"}},nodes:[text("title","primary","heading","Account settings",36,28,300,34,24,{fontWeight:650}),text("section","secondary-one","heading","Profile information",36,88,300,24,15,{fontWeight:650}),text("name-label","secondary-two","label","DISPLAY NAME",36,132,220,18,9,{letterSpacing:.8}),text("name-value","secondary-one","body","Temi Adeyemi",36,158,420,38,14),text("email-label","secondary-two","label","EMAIL ADDRESS",36,220,220,18,9,{letterSpacing:.8}),text("error","secondary-one","caption","That address is already linked to another account.",36,270,400,28,11,{color:"#B42318"}),text("action","primary","label","Save changes",500,344,120,26,12,{textAlign:"center",fontWeight:650})]}},
	{ id:"mobile-interface", name:"Mobile interface", description:"A narrow mobile product screen.", category:"product-ui", purpose:"Test navigation, headings, body copy, and actions in a narrow container.", stressTests:["small-size","narrow-container","mixed-case"], aspectRatio:"9:16", recommendedRoles:roles, card:{settings:{fill:{type:"solid",color:"#F3F0E8"}},nodes:[text("nav","secondary-two","label","9:41                                      82%",20,18,185,18,9),text("title","primary","heading","Your next session",22,78,180,62,28,{fontWeight:700,lineHeight:1.05}),text("body","secondary-one","body","A focused 25-minute block is ready. Notifications will stay quiet until you finish.",22,158,180,90,14,{lineHeight:1.45}),text("metric","secondary-two","numeral","25:00",22,280,180,60,44,{fontWeight:650}),text("action","primary","label","Begin focus",22,386,180,34,14,{textAlign:"center",fontWeight:650})]}},
	{ id:"business-card", name:"Business card", description:"Identity and compact professional metadata.", category:"identity", purpose:"Test name hierarchy, contact information, and small-size legibility.", stressTests:["small-size","mixed-case","wide-container"], aspectRatio:"business-card", recommendedRoles:roles, card:{settings:{fill:{type:"solid",color:"#17302B"}},nodes:[text("brand","primary","display","NORTH / OFFICE",24,24,250,34,22,{fontWeight:700,color:"#F5F0E7",letterSpacing:-.5}),text("name","secondary-one","heading","Ife Adebayo",24,112,210,26,15,{fontWeight:650,color:"#F5F0E7"}),text("role","secondary-two","metadata","Strategy Director",24,140,180,20,10,{color:"#C9D8D2"}),text("contact","secondary-two","metadata","ife@northoffice.co\n+234 800 120 4400",310,112,210,46,10,{color:"#F5F0E7",textAlign:"right",lineHeight:1.5})]}},
	{ id:"brand-typography-sheet", name:"Brand typography sheet", description:"All semantic roles viewed together.", category:"identity", purpose:"Test the display, heading, body, and metadata roles as one system.", stressTests:["display-size","small-size","mixed-case","numerals"], aspectRatio:"3:2", recommendedRoles:roles, card:{settings:{fill:{type:"solid",color:"#EEEAE1"}},nodes:[text("primary-label","secondary-two","label","PRIMARY / DISPLAY",34,26,200,18,9,{letterSpacing:1}),text("title","primary","display","Common Ground",34,54,590,70,52,{fontWeight:700,letterSpacing:-2}),text("secondary-label","secondary-two","label","SECONDARY ONE / TEXT",34,148,220,18,9,{letterSpacing:1}),text("heading","secondary-one","heading","Ideas need room to become useful.",34,178,430,42,23,{fontWeight:650}),text("body","secondary-one","body","A clear typographic system creates rhythm without asking for attention. It helps every message find its appropriate voice.",34,235,400,78,14,{lineHeight:1.5}),text("metadata","secondary-two","metadata","SECONDARY TWO · 0123456789 · Aa Bb Cc",34,346,500,22,10,{letterSpacing:.6})]}},
	{ id:"presentation-title", name:"Presentation title", description:"A sparse title slide and presenter line.", category:"identity", purpose:"Test a large heading, subtitle, presenter metadata, and date in a sparse composition.", stressTests:["display-size","wide-container","mixed-case"], aspectRatio:"16:9", recommendedRoles:roles, card:{settings:{fill:{type:"solid",color:"#4A50FF"}},nodes:[text("title","primary","display","A quieter kind of technology",44,76,570,130,50,{fontWeight:700,lineHeight:1.02,color:"#FFFFFF",letterSpacing:-1.5}),text("subtitle","secondary-one","body","Designing tools that respect attention.",46,230,430,34,18,{color:"#FFFFFF"}),text("metadata","secondary-two","metadata","TEMI ADEYEMI · JULY 2026",46,350,340,20,10,{color:"#DADCFB",letterSpacing:1})]}},
];

export function getTypographyScenario(id: string) { return TYPOGRAPHY_SCENARIOS.find((scenario) => scenario.id === id); }

export function createCardFromScenario(scenario: TypographyScenarioDefinition): EditorCard {
	const size = getCardSizeFromAspectRatio(scenario.aspectRatio);
	const settings: CardSettings = { aspectRatio:scenario.aspectRatio, fill:{type:"solid",color:"#FFFFFF"}, texture:null, opacity:1, blur:0, borderWidth:0, borderStyle:"solid", borderColor:"#000000", ...scenario.card.settings };
	return { id:createId(), name:scenario.name, ...size, settings, scenario:{scenarioId:scenario.id,scenarioName:scenario.name,category:scenario.category,stressTests:[...scenario.stressTests]}, nodes:scenario.card.nodes.map((node) => node.type === "text" ? { id:createId(),type:"text",linkedNodeKey:node.key,x:node.x,y:node.y,width:node.width,height:node.height,positions:{[scenario.aspectRatio]:{x:node.x,y:node.y}},rotation:0,text:node.content,fontType:node.role === "primary" ? "primary" : node.role === "secondary-one" ? "sec1" : "sec2",fontSource:{type:"role",role:node.role},fontSize:node.fontSize,fontWeight:node.fontWeight ?? 500,lineHeight:node.lineHeight,letterSpacing:node.letterSpacing ?? 0,color:node.color ?? "#161616",textAlign:node.textAlign ?? "left",textCasing:node.textCasing ?? "none"} : {id:createId(),type:"image",linkedNodeKey:node.key,x:node.x,y:node.y,width:node.width,height:node.height,positions:{[scenario.aspectRatio]:{x:node.x,y:node.y}},rotation:0,src:node.src ?? "",imageId:null,alt:node.alt ?? "",objectFit:"cover",zoom:1,positionX:50,positionY:50,effects:{brightness:100,contrast:100,saturation:100,blur:0,grayscale:0,sepia:0},opacity:1,texture:null}) };
}
